#!/bin/sh -ex

export MAKEFLAGS="-j 9"
make clean
make compile

for file in daniel_plot1.csv daniel_plot2.csv daniel_plot3.csv daniel_plot4.csv vtune-fc.csv; do
  echo "running $file..."
  taskset -a -c 0 ./tnn -t -b -p parameters/$file -o benchmarks/$file -i t2r_gemmLU,t2r_gemmLU_block,t2r_gemmLU_unroll
done
