#!/bin/sh -ex

export MAKEFLAGS="-j 17"
make clean
make compile

for file in rudy_plot1.csv rudy_plot2.csv; do
  echo "running $file..."
  taskset -a -c 0 ./tnn -t -b -p parameters/$file -o benchmarks/$file -i t2r_gemmLU_block,t2r_ur_gemmLU_block,t2r_avx2u_ur_gemmLU_block,t2r_avx2u_gemmLU_block,t2r_avx2u_permute_ur_gemmLU_block,t2r_avx2u_permute_gemmLU_block,t2r_avx512u_ur_gemmLU_block,t2r_avx512u_gemmLU_block
done
