#!/bin/sh -ex

export MAKEFLAGS="-j 17"
make clean
make compile

for file in incr_c.csv incr_hw.csv; do
  echo "running $file..."
  taskset -a -c 0 ./tnn -t -b -p parameters/$file -o benchmarks/$file -i t2r_gemmLU,t2r_gemmLU_unroll,t2r_gemmLU_lord,t2r_gemmLU_block
done
