#!/bin/sh -ex

echo "0" | sudo tee /sys/devices/system/cpu/cpufreq/boost

scripts/notify "make" "building files"

export MAKEFLAGS="-j 9"
make clean
make

scripts/notify "begun" "running benchmarks"

for file in $(ls parameters); do
  echo "running $file..."
  taskset -a -c 0 ./tnn -t -b -p parameters/$file -o results/csvs/final/$file
  scripts/notify "${file}" "${file} benchmark done"
done

scripts/notify "all done" "completed"
