#!/bin/sh -ex

export MAKEFLAGS="-j 9"
make clean
make

for file in incr_c.csv fc.csv; do
  echo "running $file..."
  taskset -a -c 0 ./tnn -t -b -p parameters/$file -o results/csvs/fc_vs_incr_c/$file -i original,best_impl_avx512
done

# Purpose: Send notification to phone - push/send message ios and android using API from my Linux box/vm/server
# Author: Vivek Gite
# Set API stuff 
_token='a7gctg67jfx5w7penvj3hexk5giq6m'
_user='umygk19bmycth1p26iokc5yr2g35yi'
 
# Send message to pushover
curl -s \
     --form-string "token=${_token}" \
     --form-string "user=${_user}" \
     --form-string "title=$incr_c vs fc done" \
     --form-string "message=$incr_c vs fc done" \
     https://api.pushover.net/1/messages.json
