#!/bin/sh -ex

echo "0" | sudo tee /sys/devices/system/cpu/cpufreq/boost

sh scripts/bench_fc_vs_incr_c
sh scripts/bench_data_order
sh scripts/bench_ternary_operator
sh scripts/bench_tmacros
sh scripts/bench_sinline
sh scripts/bench_naive_tern2row
sh scripts/bench_improved_tern2row
